version: "3"
services:
  server:
    build: ./server
    image: "enjoei-server"
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  app:
    build: ./app
    image: "enjoei-app:latest"
    ports:
     - "80:80"
